services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
    env_file:
      - .env

    networks:
      - app-network



networks:
  app-network:
    driver: bridge
